version: '3'

services:

  web:
    build: ./web_app
    container_name: sqreenbot_web
    env_file: ./web.env
    command: /code/run_web.sh
    volumes:
      - ./web_app:/code
    ports:
      - 8443:8443

  nginx:
    build: ./nginx
    container_name: sqreen_nginx
    restart: always
    env_file: ./web.env
    volumes:
      - ./web_app/static_root:/code/static_root
      - ./web_app/media:/code/media
      - ./nginx/logs:/var/log/nginx
      - ./nginx/ssl:/code/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

