# Generated by Django 3.0.4 on 2020-03-20 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='LiteraryWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Author')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('description', models.TextField()),
                ('length', models.IntegerField()),
                ('class_category', models.CharField(default='all', max_length=8)),
                ('date_parse', models.DateTimeField(auto_now=True)),
                ('base_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Category')),
                ('literary_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.LiteraryWork')),
            ],
        ),
    ]
