# Generated by Django 3.0.4 on 2020-03-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20200320_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор-письменник', 'verbose_name_plural': 'Автори-письменники'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='literarywork',
            options={'verbose_name': 'Художній твір', 'verbose_name_plural': 'Художні твори'},
        ),
        migrations.AlterModelOptions(
            name='schoolwork',
            options={'verbose_name': 'Шкільний твір', 'verbose_name_plural': 'Шкільні твори'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Тип шкільного твору', 'verbose_name_plural': 'Типи шкільних творів'},
        ),
    ]
