# Generated by Django 3.0.4 on 2020-03-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20200320_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.CharField(max_length=256, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='literarywork',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='literarywork',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='base_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='class_category',
            field=models.CharField(default='all', max_length=8, verbose_name='Клас школи'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='date_parse',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата занесення у базу'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='description',
            field=models.TextField(verbose_name='Текст твору'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='length',
            field=models.IntegerField(verbose_name='К-сть слів'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='literary_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.LiteraryWork', verbose_name='Художній твір'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='work_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.WorkType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Назва типу'),
        ),
    ]
