# Generated by Django 3.0.4 on 2020-03-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20200320_1537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolwork',
            options={'ordering': ['title', '-length'], 'verbose_name': 'Шкільний твір', 'verbose_name_plural': 'Шкільні твори'},
        ),
    ]
