# Generated by Django 3.0.4 on 2020-03-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20200320_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolwork',
            name='url',
            field=models.URLField(default='https://google.com'),
        ),
    ]
