# Generated by Django 3.0.4 on 2020-03-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_schoolwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolwork',
            name='file_id',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='schoolwork',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Твір валідний?'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='url',
            field=models.URLField(default='https://google.com', verbose_name='Джерело'),
        ),
    ]
