# Generated by Django 3.0.4 on 2020-03-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20200321_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolwork',
            options={'ordering': ['-title', '-length', 'file_id'], 'verbose_name': 'Шкільний твір', 'verbose_name_plural': 'Шкільні твори'},
        ),
        migrations.AddField(
            model_name='schoolwork',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='К-сть попадань у загальну видачу'),
        ),
        migrations.AddField(
            model_name='schoolwork',
            name='top_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='К-сть попадань у топ-видачу'),
        ),
    ]
