# Generated by Django 3.0.4 on 2020-03-21 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20200321_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literarywork',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='base_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='literary_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.LiteraryWork', verbose_name='Художній твір'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.WorkType', verbose_name='Тип'),
        ),
    ]
