# Generated by Django 3.0.4 on 2020-03-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20200321_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_by_title', models.IntegerField(blank=True, default=0, null=True, verbose_name='К-сть пошуків по заголовку')),
            ],
            options={
                'verbose_name': 'Аналітика',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id чату')),
                ('user_name', models.CharField(max_length=256, verbose_name='Telegram username')),
                ('full_name', models.CharField(max_length=256, verbose_name="Ім'я")),
            ],
            options={
                'verbose_name': 'Користувачі',
            },
        ),
    ]
