# Generated by Django 3.0.4 on 2020-03-21 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_analytic_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolwork',
            options={'ordering': ['-title', '-top_count'], 'verbose_name': 'Шкільний твір', 'verbose_name_plural': 'Шкільні твори'},
        ),
    ]
