# Generated by Django 3.0.4 on 2020-03-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20200321_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolwork',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='К-сть заг-видачі'),
        ),
        migrations.AlterField(
            model_name='schoolwork',
            name='top_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='К-сть топ-видачі'),
        ),
    ]
