# Generated by Django 3.0.4 on 2020-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_auto_20200321_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='full_name',
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name="Ім'я"),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Прізвище'),
        ),
        migrations.AddField(
            model_name='users',
            name='search_count',
            field=models.IntegerField(default=0, verbose_name='К-сть пошуків'),
        ),
    ]
