# Generated by Django 3.0.4 on 2020-03-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20200321_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.AddField(
            model_name='analytic',
            name='name',
            field=models.CharField(default='Аналітика', max_length=256, verbose_name='Назва'),
        ),
    ]
