# Generated by Django 3.0.4 on 2020-03-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20200321_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
