# Generated by Django 3.0.4 on 2020-03-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20200321_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={'verbose_name': 'Аналітика', 'verbose_name_plural': 'Аналітика'},
        ),
    ]
