# Generated by Django 3.0.4 on 2020-03-21 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20200321_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolwork',
            options={'ordering': ['-top_count', '-title'], 'verbose_name': 'Шкільний твір', 'verbose_name_plural': 'Шкільні твори'},
        ),
    ]
