# Generated by Django 3.0.4 on 2020-05-02 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_auto_20200321_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=512, verbose_name='Запит')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата пошуку')),
                ('response_count', models.IntegerField(default=0, verbose_name='К-сть видачі')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.User', verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Історія пошуку',
                'verbose_name_plural': 'Історія пошуку',
                'ordering': ['-date'],
            },
        ),
    ]
