# Generated by Django 3.0.4 on 2020-05-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_searchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPerekaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('description', models.CharField(max_length=64)),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_perekazu', to='bot.LiteraryWork')),
            ],
            options={
                'verbose_name': 'Аудіо переказ',
                'verbose_name_plural': 'Аудіо перекази',
            },
        ),
    ]
