# Generated by Django 3.0.4 on 2020-05-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_feedback_sendmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата відправлення'),
        ),
    ]
