# Generated by Django 3.0.4 on 2020-05-13 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20200513_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.User', verbose_name='Від кого'),
        ),
        migrations.AlterField(
            model_name='sendmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.User', verbose_name='Кому'),
        ),
    ]
