# Generated by Django 3.0.4 on 2020-05-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20200513_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_create',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отримання'),
        ),
    ]
