# Generated by Django 3.0.4 on 2020-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_historyevent_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyevent',
            name='category',
            field=models.CharField(blank=True, default='Others', max_length=64, null=True),
        ),
    ]
