# Generated by Django 3.0.4 on 2020-06-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_historyevent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyevent',
            name='sub_category',
            field=models.CharField(blank=True, default='Others', max_length=64, null=True, verbose_name='Під-категорія'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='category',
            field=models.CharField(blank=True, default='Others', max_length=64, null=True, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='description',
            field=models.TextField(verbose_name='Подія'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='source_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Джерело'),
        ),
        migrations.AlterField(
            model_name='historyevent',
            name='year',
            field=models.CharField(max_length=62, verbose_name='Рік'),
        ),
    ]
