# Generated by Django 3.0.4 on 2020-08-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0030_auto_20200621_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Аналітика', max_length=256, verbose_name='Назва')),
                ('request_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=256)),
                ('url', models.URLField(max_length=1024)),
                ('screenshot', models.ImageField(upload_to='screenshots')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Analytic',
        ),
        migrations.RemoveField(
            model_name='audioperekaz',
            name='work',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='parent_msg',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoryEvent',
        ),
        migrations.RemoveField(
            model_name='literarywork',
            name='author',
        ),
        migrations.RemoveField(
            model_name='schoolwork',
            name='base_category',
        ),
        migrations.RemoveField(
            model_name='schoolwork',
            name='literary_work',
        ),
        migrations.RemoveField(
            model_name='schoolwork',
            name='work_type',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='service',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sendmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='AudioPerekaz',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='LiteraryWork',
        ),
        migrations.DeleteModel(
            name='SchoolWork',
        ),
        migrations.DeleteModel(
            name='SearchHistory',
        ),
        migrations.DeleteModel(
            name='SendMessage',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
