# Generated by Django 3.0.4 on 2020-08-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_auto_20200803_2032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='request_count',
        ),
        migrations.AlterField(
            model_name='bot',
            name='name',
            field=models.CharField(default='SqreenshotBot', max_length=32),
        ),
    ]
